import React from "react";
import { Anchor, Box, Image, Heading, Text } from "grommet";
import resumePDF from "../../assets/resume.pdf";

export default function Resume() {
	return (
		<Box pad="xlarge">
			<Heading margin="xsmall" level="2">
				I'm a versatile full-stack developer with a strong background in UIX
				design
			</Heading>

			<Box margin={{ vertical: "medium" }}>
				<Anchor
					size="large"
					color="#2e4aed"
					label="Download my full resume"
					href={resumePDF}
					download="florence-kamp.pdf"
				/>
			</Box>
			<Heading level="4">Languages & Tools</Heading>
			<Text margin={{ left: "medium", bottom: "medium" }} align="left">
				<Image
					margin="small"
					src="https://raw.githubusercontent.com/devicons/devicon/master/icons/bootstrap/bootstrap-plain-wordmark.svg"
					alt="bootstrap"
					width="64"
					height="64"
				/>
				<Image
					margin="small"
					src="https://raw.githubusercontent.com/gilbarbara/logos/804dc257b59e144eaca5bc6ffd16949752c6f789/logos/bulma.svg"
					alt="bulma"
					width="64"
					height="64"
				/>
				<Image
					margin="small"
					src="https://raw.githubusercontent.com/devicons/devicon/master/icons/express/express-original-wordmark.svg"
					alt="express"
					width="64"
					height="64"
				/>
				<Image
					margin="small"
					src="https://www.vectorlogo.zone/logos/figma/figma-icon.svg"
					alt="figma"
					width="64"
					height="64"
				/>
				<Image
					margin="small"
					src="https://www.vectorlogo.zone/logos/graphql/graphql-icon.svg"
					alt="graphql"
					width="64"
					height="64"
				/>
				<Image
					margin="small"
					src="https://www.vectorlogo.zone/logos/heroku/heroku-icon.svg"
					alt="heroku"
					width="64"
					height="64"
				/>
				<Image
					margin="small"
					src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg"
					alt="html5"
					width="64"
					height="64"
				/>
				<Image
					margin="small"
					src="https://www.vectorlogo.zone/logos/adobe_illustrator/adobe_illustrator-icon.svg"
					alt="illustrator"
					width="64"
					height="64"
				/>
				<Image
					margin="small"
					src="https://www.vectorlogo.zone/logos/invisionapp/invisionapp-icon.svg"
					alt="invision"
					width="64"
					height="64"
				/>
				<Image
					margin="small"
					src="https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg"
					alt="javascript"
					width="64"
					height="64"
				/>
				<Image
					margin="small"
					src="https://www.vectorlogo.zone/logos/mochajs/mochajs-icon.svg"
					alt="mocha"
					width="64"
					height="64"
				/>
				<Image
					margin="small"
					src="https://raw.githubusercontent.com/devicons/devicon/master/icons/mongodb/mongodb-original-wordmark.svg"
					alt="mongodb"
					width="64"
					height="64"
				/>
				<Image
					margin="small"
					src="https://raw.githubusercontent.com/devicons/devicon/master/icons/mysql/mysql-original-wordmark.svg"
					alt="mysql"
					width="64"
					height="64"
				/>
				<Image
					margin="small"
					src="https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original-wordmark.svg"
					alt="nodejs"
					width="64"
					height="64"
				/>
				<Image
					margin="small"
					src="https://raw.githubusercontent.com/devicons/devicon/master/icons/photoshop/photoshop-line.svg"
					alt="photoshop"
					width="64"
					height="64"
				/>
				<Image
					margin="small"
					src="https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original-wordmark.svg"
					alt="react"
					width="64"
					height="64"
				/>
				<Image
					margin="small"
					src="https://raw.githubusercontent.com/devicons/devicon/master/icons/redux/redux-original.svg"
					alt="redux"
					width="64"
					height="64"
				/>
				<Image
					margin="small"
					src="https://www.vectorlogo.zone/logos/sketchapp/sketchapp-icon.svg"
					alt="sketch"
					width="64"
					height="64"
				/>
				<Image
					margin="small"
					src="https://www.vectorlogo.zone/logos/sqlite/sqlite-icon.svg"
					alt="sqlite"
					width="64"
					height="64"
				/>
				<Image
					margin="small"
					src="https://raw.githubusercontent.com/devicons/devicon/d00d0969292a6569d45b06d3f350f463a0107b0d/icons/webpack/webpack-original-wordmark.svg"
					alt="webpack"
					width="64"
					height="64"
				/>
			</Text>
			<Heading level="4">Top Languages</Heading>
			<Box height="120px" width="480px" overflow="hidden" align="center">
				<Image
					fill="horizontal"
					align="left"
					src="https://github-readme-stats.vercel.app/api/top-langs?username=flokamp&show_icons=true&locale=en&layout=compact&hide_border=true&theme=graywhite&hide_title=true&langs_count=4"
					alt="flokamp"
				/>
			</Box>
		</Box>
	);
}
